---
- src: git@github.com:xussof/software_docker
  scm: git
  version: master
  name: software_docker

- src: git@github.com:xussof/software_pip-docker
  scm: git
  version: master
  name: software_pip-docker
#Necesita pip install docker
